SELECT	TMOV.CODCOLIGADA, 
TMOV.CODFILIAL, 
TMOV.CODTMV, 
TMOV.IDMOV, 
TMOV.DATAEMISSAO, 
TMOV.CODCFO, 
FCFO.NOME, 
FCFO.NOMEFANTASIA,
TMOVAPROVA.DATAAPROVACAO, 
TMOVAPROVA.CODUSUARIO,
TMOVRATCCU.CODCCUSTO,
ISNULL (TMOV.VALORBRUTOINTERNO, TMOV.VALORBRUTO) AS VALOR,
TMOV.OBSERVACAO

FROM TMOV, TMOVAPROVA, FCFO, TMOVRATCCU

WHERE 
TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA AND
TMOV.IDMOV = TMOVAPROVA.IDMOV AND
TMOV.CODCOLIGADA = TMOVRATCCU.CODCOLIGADA AND
TMOV.IDMOV = TMOVRATCCU.IDMOV AND
TMOV.CODCFO = FCFO.CODCFO AND
TMOV.CODCOLIGADA = 7 AND 
TMOV.CODFILIAL NOT IN (31,32,33,34,35,36,37) AND
TMOV.CODTMV LIKE ('1.1.%') AND 
TMOV.STATUS <> 'C' AND
TMOVRATCCU.CODCCUSTO NOT LIKE ('01.%') AND 
TMOVRATCCU.CODCCUSTO NOT LIKE ('51.%') AND 
TMOVRATCCU.CODCCUSTO NOT LIKE ('07.%') AND 
TMOVRATCCU.CODCCUSTO NOT LIKE ('06.%') AND 
TMOVRATCCU.CODCCUSTO NOT LIKE ('04.%') AND 
TMOVRATCCU.CODCCUSTO NOT LIKE ('05.%') AND
TMOV.DATAEMISSAO >= '26/03/2019' and TMOVRATCCU.CODCCUSTO = '03.0003'
