select t.CODPROJETO,t.CODTALHAO,i.CODTIPOINTERVENCAO,p.DESCPRODUTO,sum(m.VOLCORRIGIDO) as Volume_m3, MONTH(S.DATAINICIO) AS MES, YEAR(S.DATAINICIO) AS ANO
from EVTMOVMADEIRA m 
join EVTSILVICULTURA s on s.SEQATIVIDADE = m.SEQATIVIDADE
join INVPRODUTO p on p.CODPRODUTO = m.CODPRODUTO 
join CADTALHAO t on t.CHATALHAO = s.CHATALHAO
join ETQAUTORIZAPRODUTO ap on ap.CODAUTORIZAINTERV = m.CODAUTORIZAINTERV and ap.CODPRODUTO = m.CODPRODUTO
join CADINTERVENCAO i on i.CODAUTORIZAINTERV = ap.CODAUTORIZAINTERV
join EVTATIVIDADE a on a.CODATIVIDADE = s.CODATIVIDADE
where t.CODPROJETO IN ( 'SIL' , 'BOC', 'K_8')
  and YEAR(s.DATAINICIO) =2016
  and a.NOMEATIVIDADE in ( 'CARGA EXPORTACAO' , 'CARGA SERRARIA' ) 
  AND I.FECHADO = 1 
group by t.CODPROJETO,t.CODTALHAO,i.CODTIPOINTERVENCAO,p.DESCPRODUTO,S.DATAINICIO  
order by 1,2,4