SELECT * FROM (
SELECT TMOV.CODCOLIGADA,TMOV.CODFILIAL,'VENDA' STD,TITMMOV.CODTBORCAMENTO,O.DESCRICAO,FCFO.NOME CLIENTE,TMOV.NUMEROMOV #NF,TMOV.DATAEMISSAO,TITMMOV.QUANTIDADE,
 TITMMOV.PRECOUNITARIO,TITMMOV.CODUND,TMOV.FRETECIFOUFOB AS FRETE,ISNULL(ROUND(TMOV.VALORDESC * TITMMOV.VALORBRUTOITEM / TMOV.VALORBRUTO,2),0) AS VALORDESC
 ,TMOV.STATUS,P.NOMEFANTASIA PRODUTO
 ,CASE WHEN TMOV.SEGUNDONUMERO <> '' THEN TMOV.SEGUNDONUMERO ELSE 'N/I' END AS INVOICE,TMOV.IDMOV,
 DATEPART(YY,TMOV.DATAEMISSAO)AS ANO
 ,TITMMOV.QUANTIDADE*TITMMOV.PRECOUNITARIO AS TOT,
 DATEPART(DAY, TMOV.DATAEMISSAO) AS DIA,
 DATEPART(MONTH, TMOV.DATAEMISSAO)AS MES,
 TH.HISTORICOLONGO,
 GP.DESCRICAO AS PAIS,
 TC.FSC,
 TC.FETHAB AS FERROVIA
 

FROM TMOV
 INNER JOIN TITMMOV (NOLOCK) ON TMOV.CODCOLIGADA=TITMMOV.CODCOLIGADA AND TMOV.IDMOV=TITMMOV.IDMOV
 INNER JOIN FCFO (NOLOCK) ON TMOV.CODCFO=FCFO.CODCFO 
 INNER JOIN TPRODUTO P (NOLOCK) ON TITMMOV.IDPRD=P.IDPRD AND P.CODCOLPRD = 0
 LEFT JOIN TTBORCAMENTO O ON O.CODTBORCAMENTO = TITMMOV.CODTBORCAMENTO AND O.CODCOLIGADA=0
 LEFT JOIN TMOVHISTORICO TH ON TH.CODCOLIGADA = TMOV.CODCOLIGADA AND TH.IDMOV = TMOV.IDMOV
 LEFT JOIN GPAIS GP ON GP.IDPAIS = FCFO.IDPAIS
 LEFT JOIN TMOVCOMPL TC ON TC.CODCOLIGADA = TMOV.CODCOLIGADA AND TC.IDMOV = TMOV.IDMOV

WHERE TMOV.CODTMV IN ('2.2.03','2.2.04','2.2.32') AND TMOV.STATUS <> 'C'

UNION ALL

SELECT TMOV.CODCOLIGADA,TMOV.CODFILIAL,'DEVOLUCAO' STD,TITMMOV.CODTBORCAMENTO,O.DESCRICAO,FCFO.NOME CLIENTE,TMOV.NUMEROMOV #NF,TMOV.DATAEMISSAO,TITMMOV.QUANTIDADE *-1,
 TITMMOV.PRECOUNITARIO,TITMMOV.CODUND,TMOV.FRETECIFOUFOB AS FRETE,ISNULL(ROUND(TMOV.VALORDESC * TITMMOV.VALORBRUTOITEM / TMOV.VALORBRUTO,2),0) AS VALORDESC
 ,TMOV.STATUS,P.NOMEFANTASIA PRODUTO
 ,CASE WHEN TMOV.SEGUNDONUMERO <> '' THEN TMOV.SEGUNDONUMERO ELSE 'N/I' END AS INVOICE,TMOV.IDMOV,
 DATEPART(YY,TMOV.DATAEMISSAO)AS ANO
 ,TITMMOV.QUANTIDADE*TITMMOV.PRECOUNITARIO*-1 AS TOT,
 DATEPART(DAY, TMOV.DATAEMISSAO) AS DIA,
 DATEPART(MONTH, TMOV.DATAEMISSAO)AS MES,
 TH.HISTORICOLONGO,
 GP.DESCRICAO AS PAIS,
 TC.FSC,
 TC.FETHAB AS FERROVIA
 

FROM TMOV
 INNER JOIN TITMMOV (NOLOCK) ON TMOV.CODCOLIGADA=TITMMOV.CODCOLIGADA AND TMOV.IDMOV=TITMMOV.IDMOV
 INNER JOIN FCFO ON TMOV.CODCFO=FCFO.CODCFO 
 INNER JOIN TPRODUTO P (NOLOCK) ON TITMMOV.IDPRD=P.IDPRD AND P.CODCOLPRD = 0
 LEFT JOIN TTBORCAMENTO O ON O.CODTBORCAMENTO = TITMMOV.CODTBORCAMENTO AND O.CODCOLIGADA=0
 LEFT JOIN TMOVHISTORICO TH ON TH.CODCOLIGADA = TMOV.CODCOLIGADA AND TH.IDMOV = TMOV.IDMOV
 LEFT JOIN GPAIS GP ON GP.IDPAIS = FCFO.IDPAIS
 LEFT JOIN TMOVCOMPL TC ON TC.CODCOLIGADA = TMOV.CODCOLIGADA AND TC.IDMOV = TMOV.IDMOV

WHERE TMOV.CODTMV IN ('1.2.20','1.2.21','1.2.22','1.2.23') AND TMOV.STATUS <> 'C'

)A
WHERE A.ANO >= 2017 AND A.CODCOLIGADA=1