select T.CODPROJETO,t.CODTALHAO,t.CHATALHAO,i.CODTIPOINTERVENCAO,YEAR(i.DATAINICIO) as ANO
  , p.DESCPRODUTO
  , m.VOLMEDIDO , u.SIGLAUNIDADE
  , ROUND(isnull(m.VOLCORRIGIDO, case when u.SIGLAUNIDADE ='st' then m.VOLMEDIDO/1.5 else m.VOLMEDIDO end),1) as CARGA
 from EVTSILVICULTURA s 
  join EVTMOVMADEIRA m on m.SEQATIVIDADE = s.SEQATIVIDADE
  join EVTATIVIDADE a on a.CODATIVIDADE = s.CODATIVIDADE 
  join AUXUNIDADE u on u.CODUNIDADE = a.CODUNIDADE
  join viewrptAREAS t on t.CHATALHAO = s.CHATALHAO
  join CADINTERVENCAO i on i.CODAUTORIZAINTERV = m.CODAUTORIZAINTERV
  join INVPRODUTO p on p.CODPRODUTO = m.CODPRODUTO
 where a.NOMEATIVIDADE like 'CARGA%' and t.CODPROJETO = 'SIL' and YEAR(i.DATAINICIO) >=2012